[package]
name = "longferris"
version = "0.1.0"
authors = ["ikanago <ikanago-dev@protonmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ikanago/longferris"
edition = "2021"

[dependencies]

[profile.dev]
debug = 0

